// <auto-generated />
namespace WebApplicationGrupp13.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class filuppladdning_informel_utbildning : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(filuppladdning_informel_utbildning));
        
        string IMigrationMetadata.Id
        {
            get { return "202004210901255_filuppladdning_informel_utbildning"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
