// <auto-generated />
namespace WebApplicationGrupp13.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class bytte_filtyp_i_formalblogpost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bytte_filtyp_i_formalblogpost));
        
        string IMigrationMetadata.Id
        {
            get { return "202004141321218_bytte_filtyp_i_formalblogpost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
